---
title: "Introduction"
output: html_document
bibliography: bibliography.bib
---

As ecology has progressed as a quantitative discipline and the questions ecologists ask have become more complicated, the statistical techniques ecologists use have increased in their flexibility to model complex relationships. Two of the most popular and powerful techniques now in use are generalized additive models [GAMs; @Wood:2006vg] for modelling non-linear regression functions, and generalized linear mixed models ["hierarchical generalized linear models" HGLMs or simply "hierarchical models"; @Bolker:2009cs, @gelman2013bayesian] for modelling between-group variability in regression relationships. 


At first glance, GAMs and HGLMs are very different tools. GAMs are used to estimate smooth functional relationships between predictor variables and the response. The assumption here is that the phenomena under investigation is not linear (in the GLM sense) but is a function of the predictor variables. An example of such a relationship would be a marine population's distribution as a function of depth or [*say something here about some other topic, Dave doesn't know about proper ecology*]. HGLMs, on the other hand, are used to estimate linear relationships between predictor variables and response, but impose a structure where predictors are organized into groups (often referred to as "blocks") and the relationships between predictor and response may differ between those groups. Groups may be as small as to have one for each individual or as large as two split the samples into two groups. Either or both slope and intercept may be subject to grouping. A typical example of HGLM use might be to include site-specific effects in a model of counts, or to model individual level heterogeneity in samples of multiple samples of individuals.

At their core, though, GAMs and HGLMs use very similar statistical machinery: penalized maximum likelihood. GAMs fit smooth curves by finding combinations of simpler curves that best fit the observed data while simulatenously penalizing overly wiggly curves. HGLMs fit group-level predictors while penalizing how far each group level parameter deviates from the average parameter value across all groups (see section II for more details on these connections). For both GAMs and HGLMs, the principle concept is that we can efficiently fit potentially highly variable models by "pooling" parameter estimates towards one another. These connections are so deep that HGLMs and GAMs can both be fit using the same software. (*not sure whether this is too technical for this section? Could go later? Agree we need something to build towards next para tho...*)

Given this connection, there is an obvious extension to the standard GAM framework: allow the smooth functional relationship between predictor and response to vary between different grouping levels, but so that the different functions are in some sense pooled toward each other. We often want to know both how the functional relationship between varies between groups, and if there is a strong relationship on average across groups. We will refer to this type of model as a *hierarchical GAM*.

There are many potential uses for hierarchical GAMs. For example, estimating how mortality rates of multiple species in a community respond to a common temperature gradient. Each species will typically have its own response function, but since the species all overlap in range, they should have similar responses over at least some temperature range. Estimating a single temperature-mortality relationship could result in a single function that did not fit any species well. Alternatively, estimating a seperate function for each species throws away a lot of shared information and could result in highly noisy function estimates if there were only a few data points for each species. Ideally, we would want a hierachical model that fit a single global temperature-mortality curve plus species-specific curves that were penalized to be close to the mean function. **this seems like the kind of thing we'd like to show in simulation**

The capability to fit hierarchical GAMs already exists in the popular *mgcv* package for the R statistical programming language, but many ecologists are not aware of the different options available, what the trade-offs between these models might be, and what different choices of group-wise smoothers assume about the underlying ecological relationships. This paper will cover the different approaches to group-level smoothing, the options for each one and why a user might choose it, and demonstrate the different approaches across a range of case studies. 

This paper is divided into six sections. Part II is a brief (and friendly) review of how penalized spline regression and hierarchical models work, focusing on the connections between the two techniques. In part III, we discuss different ways of modelling hierarchical additive models, what assumptions each model makes about how information is shared between groups, and different ways of specifying these models in *mgcv*. In part IV, we discuss some of the computational and statistical issues involved in fitting hierarchical GAMs in *mgcv*. In part V, we discuss some of the tools available for plotting model output and assessing model goodness of fit. Finally, in part VI, we work through a few examples of analyses using this approach, to demonstrate the modelling process and how hierarchical GAMs can be incorporated into the quantitative ecologist's toolbox. 




