---
title: "Hierarchical Generalized Additive Models: an introduction with mgcv"
header-includes: 
  - \usepackage{lineno}
    \linenumbers
compact-title: FALSE
output:
  pdf_document:
    fig_caption: yes
    keep_tex: yes
documentclass: "article"
classoption: "12pt"
geometry: left=2.5cm,right=2.5cm,top=2.5cm,bottom=2.5cm,headheight=12pt,letterpaper
bibliography: bibliography.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE, cache=TRUE)
library(mgcv)
library(gamm4)
library(tidyr)
library(ggplot2)
library(viridis)
library(cowplot)
library(kableExtra)
library(knitr)
library(tibble)

#Set the default theme for ggplot objects to theme_bw()
theme_set(theme_bw())
theme_update(panel.grid = element_blank())
```


```{r child = '01-intro.Rmd'}
```

```{r child = '02-gams.Rmd'}
```

```{r child = '03-hierarchical_gams.Rmd'}
```

```{r child = '04-computational_and_statistical_issues.Rmd'}
```

```{r child = '05-examples.Rmd'}
```

# Bibliography
